<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    fill="currentColor"
  >
    <rect
      x="6"
      y="4"
      width="2"
      height="16"
    ></rect><rect
      x="16"
      y="4"
      width="2"
      height="16"
    ></rect>
  </svg>
</template>
